my_env =  {'LC_PAPER': 'en_US.UTF-8', 'XDG_VTNR': '7', 'MANPATH': ':/opt/puppetlabs/puppet/share/man', 'LC_ADDRESS': 'en_US.UTF-8', 'XDG_SESSION_ID': 'c2', 'TERM_PROGRAM': 'vscode', 'CLUTTER_IM_MODULE': 'xim', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/roees', 'LC_MONETARY': 'en_US.UTF-8', 'GPG_AGENT_INFO': '/home/roees/.gnupg/S.gpg-agent:0:1', 'VTE_VERSION': '4402', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'ROS_PACKAGE_PATH': '/home/roees/tmp_ws/src:/opt/ros/kinetic/share', 'TERM_PROGRAM_VERSION': '1.62.2', 'BYOBU_CONFIG_DIR': '/home/roees/.byobu', 'ROS_MASTER_URI': 'http://localhost:11311', 'LC_NUMERIC': 'en_US.UTF-8', 'WINDOWID': '55432215', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'Unity', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/3431', 'ROS_PYTHON_VERSION': '2', 'OLDPWD': '/home/roees/projects/RL_ROS', 'BYOBU_TTY': '/dev/pts/3', 'ROS_VERSION': '1', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'BYOBU_READLINK': 'readlink', 'USER': 'roees', 'QT_ACCESSIBILITY': '1', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_TELEPHONE': 'en_US.UTF-8', 
 'LD_LIBRARY_PATH': '/home/roees/tmp_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu', 'BYOBU_RUN_DIR': '/dev/shm/byobu-roees-gzc6X0xd', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'BYOBU_DISTRO': 'Ubuntu', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'SSH_AUTH_SOCK': '/home/roees/.byobu/.ssh-agent', 'BYOBU_DATE': '%Y-%m-%d ', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 
 'TMUX': 'my-other-session-2,4420,15', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'BYOBU_BACKEND': 'tmux', 'BYOBU_SED': 'sed', 
 'PATH':                         '/opt/ros/kinetic/bin:/home/roees/bin:/home/roees/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin', 'DESKTOP_SESSION': 'ubuntu', 'QT_IM_MODULE': 'ibus', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'BYOBU_DARK': '#333333', 'LC_IDENTIFICATION': 'en_US.UTF-8', 'JOB': 'gnome-session', 
 'PWD': '/home/roees/tmp_ws',          'XDG_SESSION_TYPE': 'x11', 'XMODIFIERS': '@im=ibus', 'BYOBU_ULIMIT': 'ulimit', 'LANG': 'en_US.UTF-8', 'GDK_BACKEND': 'x11', 'GDM_LANG': 'en_US', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LC_MEASUREMENT': 'en_US.UTF-8', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS': '', 'CHROME_DESKTOP': 'code-url-handler.desktop', 'TMUX_PANE': '%37', 'IM_CONFIG_PHASE': '1', 'COMPIZ_CONFIG_PROFILE': 'ubuntu',
 'PS1': '\\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 
 'ROSLISP_PACKAGE_DIRECTORIES': '/home/roees/tmp_ws/devel/share/common-lisp', 
 'PAPERSIZE': 'letter', 'BYOBU_PYTHON': 'python3', 'GDMSESSION': 'ubuntu', 'BYOBU_CHARMAP': 'UTF-8', 'BYOBU_WINDOW_NAME': '-', 'HISTCONTROL': 'ignoredups:erasedups', 'GTK2_MODULES': 'overlay-scrollbar', 'SESSIONTYPE': 'gnome-session', 'BREAKPAD_DUMP_LOCATION': '/home/roees/.config/Code/exthost Crash Reports', 'HOME': '/home/roees', 'SHLVL': '4', 'XDG_SEAT': 'seat0', 'VSCODE_GIT_ASKPASS_MAIN': '/usr/share/code/resources/app/extensions/git/dist/askpass-main.js', 'APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL': 'true', 'ROS_DISTRO': 'kinetic', 'LANGUAGE': 'en_US', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'BYOBU_LIGHT': '#EEEEEE', 'PYTHONPATH': '/opt/ros/kinetic/lib/python2.7/dist-packages', 'UPSTART_EVENTS': 'started starting', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LOGNAME': 'roees', 'VSCODE_GIT_IPC_HANDLE': '/run/user/1000/vscode-git-f6b642b9fa.sock', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/home/roees/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'BYOBU_PAGER': 'sensible-pager', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-7Yv43z7BKN', 'QT4_IM_MODULE': 'xim', 'BYOBU_ACCENT': '#75507B',
 'PKG_CONFIG_PATH': '/home/roees/tmp_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig',
 'LESSOPEN': '| /usr/bin/lesspipe %s', 'PROMPT_COMMAND': 'history -a; history -c; history -r\nhistory -a; history -c; history -r', 'BYOBU_PREFIX': '/usr', 'VSCODE_GIT_ASKPASS_NODE': '/usr/share/code/code', 'GIT_ASKPASS': '/usr/share/code/resources/app/extensions/git/dist/askpass.sh', 'UPSTART_JOB': 'unity-settings-daemon', 'INSTANCE': 'Unity',
 'CMAKE_PREFIX_PATH': '/home/roees/tmp_ws/devel:/opt/ros/kinetic', 'DISPLAY': ':0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_CURRENT_DESKTOP': 'Unity', 'BYOBU_HIGHLIGHT': '#DD4814', 'GTK_IM_MODULE': 'ibus', 'NO_AT_BRIDGE': '1', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_TIME': 'en_US.UTF-8', 'LC_NAME': 'en_US.UTF-8', 'XAUTHORITY': '/home/roees/.Xauthority', 'COLORTERM': 'truecolor', 'BYOBU_TIME': '%H:%M:%S',
 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', '_': '/usr/bin/python3.6'}

my_vEnv = {'LC_PAPER': 'en_US.UTF-8', 'XDG_VTNR': '7', 'MANPATH': ':/opt/puppetlabs/puppet/share/man', 'LC_ADDRESS': 'en_US.UTF-8', 'XDG_SESSION_ID': 'c2', 'TERM_PROGRAM': 'vscode', 'CLUTTER_IM_MODULE': 'xim', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/roees', 'LC_MONETARY': 'en_US.UTF-8', 'GPG_AGENT_INFO': '/home/roees/.gnupg/S.gpg-agent:0:1', 'VTE_VERSION': '4402', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'ROS_ROOT': '/opt/ros/kinetic/share/ros', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'ROS_PACKAGE_PATH':                        '/opt/ros/kinetic/share', 'TERM_PROGRAM_VERSION': '1.62.2', 'BYOBU_CONFIG_DIR': '/home/roees/.byobu', 'ROS_MASTER_URI': 'http://localhost:11311', 'LC_NUMERIC': 'en_US.UTF-8', 'WINDOWID': '55432215', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'Unity', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/3431', 'ROS_PYTHON_VERSION': '2',                                          'BYOBU_TTY': '/dev/pts/3', 'ROS_VERSION': '1', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'BYOBU_READLINK': 'readlink', 'USER': 'roees', 'QT_ACCESSIBILITY': '1', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LC_TELEPHONE': 'en_US.UTF-8', 
 'LD_LIBRARY_PATH':                              '/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu', 'BYOBU_RUN_DIR': '/dev/shm/byobu-roees-gzc6X0xd', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'BYOBU_DISTRO': 'Ubuntu', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'SSH_AUTH_SOCK': '/home/roees/.byobu/.ssh-agent', 'BYOBU_DATE': '%Y-%m-%d ', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path',
 'VIRTUAL_ENV': '/home/roees/rl_env', 
 'TMUX': 'my-other-session-2,4420,15', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'BYOBU_BACKEND': 'tmux', 'BYOBU_SED': 'sed', 
 'PATH': '/home/roees/rl_env/bin:/opt/ros/kinetic/bin:/home/roees/bin:/home/roees/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin', 'DESKTOP_SESSION': 'ubuntu', 'QT_IM_MODULE': 'ibus', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'BYOBU_DARK': '#333333', 'LC_IDENTIFICATION': 'en_US.UTF-8', 'JOB': 'gnome-session', 
 'PWD': '/home/roees/projects/RL_ROS', 'XDG_SESSION_TYPE': 'x11', 'XMODIFIERS': '@im=ibus', 'BYOBU_ULIMIT': 'ulimit', 'LANG': 'en_US.UTF-8', 'GDK_BACKEND': 'x11', 'GDM_LANG': 'en_US', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LC_MEASUREMENT': 'en_US.UTF-8', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS': '', 'CHROME_DESKTOP': 'code-url-handler.desktop', 'TMUX_PANE': '%37', 'IM_CONFIG_PHASE': '1', 'COMPIZ_CONFIG_PROFILE': 'ubuntu',
 'PS1': '(rl_env) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ', 
 'ROSLISP_PACKAGE_DIRECTORIES': '', 
 'PAPERSIZE': 'letter', 'BYOBU_PYTHON': 'python3', 'GDMSESSION': 'ubuntu', 'BYOBU_CHARMAP': 'UTF-8', 'BYOBU_WINDOW_NAME': '-', 'HISTCONTROL': 'ignoredups:erasedups', 'GTK2_MODULES': 'overlay-scrollbar', 'SESSIONTYPE': 'gnome-session', 'BREAKPAD_DUMP_LOCATION': '/home/roees/.config/Code/exthost Crash Reports', 'HOME': '/home/roees', 'SHLVL': '4', 'XDG_SEAT': 'seat0', 'VSCODE_GIT_ASKPASS_MAIN': '/usr/share/code/resources/app/extensions/git/dist/askpass-main.js', 'APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL': 'true', 'ROS_DISTRO': 'kinetic', 'LANGUAGE': 'en_US', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'BYOBU_LIGHT': '#EEEEEE', 'PYTHONPATH': '/opt/ros/kinetic/lib/python2.7/dist-packages', 'UPSTART_EVENTS': 'started starting', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LOGNAME': 'roees', 'VSCODE_GIT_IPC_HANDLE': '/run/user/1000/vscode-git-f6b642b9fa.sock', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/home/roees/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'BYOBU_PAGER': 'sensible-pager', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-7Yv43z7BKN', 'QT4_IM_MODULE': 'xim', 'BYOBU_ACCENT': '#75507B',
 'PKG_CONFIG_PATH': '/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig',
 'LESSOPEN': '| /usr/bin/lesspipe %s', 'PROMPT_COMMAND': 'history -a; history -c; history -r\nhistory -a; history -c; history -r', 'BYOBU_PREFIX': '/usr', 'VSCODE_GIT_ASKPASS_NODE': '/usr/share/code/code', 'GIT_ASKPASS': '/usr/share/code/resources/app/extensions/git/dist/askpass.sh', 'UPSTART_JOB': 'unity-settings-daemon', 'INSTANCE': 'Unity',
 'CMAKE_PREFIX_PATH':                          '/opt/ros/kinetic', 'DISPLAY': ':0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_CURRENT_DESKTOP': 'Unity', 'BYOBU_HIGHLIGHT': '#DD4814', 'GTK_IM_MODULE': 'ibus', 'NO_AT_BRIDGE': '1', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_TIME': 'en_US.UTF-8', 'LC_NAME': 'en_US.UTF-8', 'XAUTHORITY': '/home/roees/.Xauthority', 'COLORTERM': 'truecolor', 'BYOBU_TIME': '%H:%M:%S',
 'ROS_ETC_DIR': '/opt/ros/kinetic/etc/ros', '_': '/home/roees/rl_env/bin/python'}

# import copy
my_env_mod = my_env
my_env_mod['PKG_CONFIG_PATH'] = '/home/roees/tmp_ws/devel/lib/pkgconfig:'+my_env_mod['PKG_CONFIG_PATH']
my_env_mod['LD_LIBRARY_PATH'] = '/home/roees/tmp_ws/devel/lib:'+my_env_mod['LD_LIBRARY_PATH']